/**
 * AUTO-GENERATED — do not edit manually.
 * Regenerate with: npm run generate:types
 *
 * This file is a placeholder until `npm run generate:types` is run
 * against a live backend (localhost:8000).
 *
 * Generated by openapi-typescript from http://localhost:8000/openapi.json
 */

// Placeholder export so index.ts re-export does not error
export type GeneratedApiTypes = Record<string, unknown>;
