"""add price_snapshots table

Revision ID: d8721aa82592
Revises: c1d2e3f4a5b6
Create Date: 2026-03-17 12:58:36.960757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8721aa82592'
down_revision: Union[str, Sequence[str], None] = 'c1d2e3f4a5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'snapshot_date', name='uq_price_snapshot_ticker_date')
    )
    op.create_index(op.f('ix_price_snapshots_id'), 'price_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_price_snapshots_ticker'), 'price_snapshots', ['ticker'], unique=False)
    op.drop_index(op.f('ix_holdings_ticker_portfolio'), table_name='holdings')
    op.drop_index(op.f('ix_sync_logs_user_synced'), table_name='sync_logs')
    op.drop_index(op.f('ix_transactions_portfolio_traded'), table_name='transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_transactions_portfolio_traded'), 'transactions', ['portfolio_id', 'traded_at'], unique=False)
    op.create_index(op.f('ix_sync_logs_user_synced'), 'sync_logs', ['user_id', 'synced_at'], unique=False)
    op.create_index(op.f('ix_holdings_ticker_portfolio'), 'holdings', ['ticker', 'portfolio_id'], unique=False)
    op.drop_index(op.f('ix_price_snapshots_ticker'), table_name='price_snapshots')
    op.drop_index(op.f('ix_price_snapshots_id'), table_name='price_snapshots')
    op.drop_table('price_snapshots')
    # ### end Alembic commands ###
